services:
  postgres:
    container_name: book_library_postgres
    image: postgres:15-alpine
    ports:
      - "${POSTGRES_PORT:-5432}:5432"
    environment:
      - POSTGRES_USER=${POSTGRES_USER:-book_library_user_postgres}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD:-book_library_password_postgres}
      - POSTGRES_DB=${POSTGRES_DB:-book_library}
      - POSTGRES_HOST_AUTH_METHOD=trust
      - POSTGRES_INITDB_ARGS=--auth-host=scram-sha-256
    volumes:
      - ./data/postgres:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER:-book_library_user_postgres} -d ${POSTGRES_DB:-book_library}"]
      interval: 5s
      timeout: 5s
      retries: 5
    networks:
      - book-library-network

networks:
  book-library-network:
    name: book-library-network