services:
  app:
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - "${PORT:-3001}:3001"
    volumes:
      - ./src:/usr/src/app/src
      - ./package.json:/usr/src/app/package.json
      - ./tsconfig.json:/usr/src/app/tsconfig.json
      - ./nodemon.json:/usr/src/app/nodemon.json
      - ./.env:/usr/src/app/.env
    environment:
      - NODE_ENV=development
      - POSTGRES_HOST=book_library_postgres
      - POSTGRES_PORT=5432
      - POSTGRES_USER=${POSTGRES_USER:-book_library_user_postgres}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD:-book_library_password_postgres}
      - POSTGRES_DB=${POSTGRES_DB:-book_library}
      - CHOKIDAR_USEPOLLING=true
      - CHOKIDAR_INTERVAL=1000
    env_file:
      - .env
    command: npm run dev
    networks:
      - book-library-network

networks:
  book-library-network:
    external: true